# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('apellidos', models.CharField(max_length=1000)),
                ('aniosExperiencia', models.IntegerField()),
                ('telefono', models.CharField(max_length=1000)),
                ('correo', models.CharField(max_length=1000)),
                ('tiposDeServicio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.tiposDeServicio')),
            ],
        ),
    ]
