# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('trabajador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.trabajador')),
            ],
        ),
    ]
