# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='tiposDeServicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.tiposDeServicio'),
        ),
    ]
