# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160208_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='imagen',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
